### ISSUE TITLE
Support for loading files from a local source?

### ISSUE THREAD

**Issue by leilei-** [remino/timeprox#4]
Say for like, in addition to connecting to the archive, have some way to supply a local mirror to the proxy. For stuff like:
- Filling in old missing graphics that may be saved by a later capture, ancient cache, or an old HTTrack job.
- Resolving old FTP links that some sites link to (for example, old game sites that linked to uwp or uml's ftp for file mirrors - these ofline FTPs have already been well mirrored at this point)
- Silly AI experiments of recreating cgi-bin chat rooms using GPT to make people that talk about Buffy, Scream, The Crow, The Simpsons and South Park.  (not that anyone will ever do that, just hypothetical)

**Comment by remino** [comment]
That’s likely possible. One could add a reverse proxy in the app and let a user specify a destination path on their local. I’m not actively maintaining this project—hence the late reply—but if anyone can submit a PR for this, I’d gladly review it.
